title: wrj's blog
baseURL: https://wrj97.com
languageCode: zh-hant
defaultContentLanguage: zh
enableRobotsTXT: true
theme: ananke
googleAnalytics: G-J5MLQ5ERLF
params:
  github: https://github.com/myml
staticDir:
  - static
